---
root_file: /home/bernhard/cernbox/Diss/mpw4/tb/desy_2404/elba_unbiased_V2.root
histogram_name: AnalysisDUT/RD50_MPWx_base_0/local_residuals/residualsY
lower_quantile: 0.5
upper_quantile: 99.5
x_range:
  - -200
  - 200
output_plot: output_histogram.png

