global:
  multi_threaded : true
  nmb_threads : 10
  corry_bin : corry
  template_config : dummy.cfg
  logfile : log
  output_file : out
  output_dir : output
  make_report : true
  plots_in_report:
  report_name: reports/report


scans:
  -   type : range #scan type to scan the specified config file for the speced parameter in the speced range
      param : EventLoaderEUDAQ2.mpw3_tshift
      lo : -500
      hi : +500
      inc : +20
      template_config : dummy.cfg
      search_pattern : run001313
      replace_pattern : run001314
      output_dir : out1
  -   type: range
      param: EventLoaderEUDAQ2.mpw3_tshift
      lo: -500
      hi: +500
      inc: +20
      template_config: dummy.cfg
      search_pattern: run001313
      replace_pattern: run001315
      output_dir : out2
  -   type: cfg_replace #scan type to run corry with the speced config file but replace all "search_pattern" with "replace_pattern"
      template_config: foo.cfg
      search_pattern: crap_results
      replace_pattern: good_results
