keys_to_extract:
  - key: AnalysisDUT/RD50_MPWx_0/local_residuals/residualsX
    name: "$\\sigma_x$"
    #x_range: [0, 20]
    #y_range: [-10, 10]
  - key: AnalysisDUT/RD50_MPWx_0/local_residuals/residualsY
    name: "$\\sigma_y$"
    #x_range: [0, 20]
    #y_range: [-15, 15]
  - key: AnalysisEfficiency/RD50_MPWx_0/chipEfficiencyMap_trackPos_TProfile
    name: "$\\epsilon$"
    #x_range: [0, 20]
    #y_range: [95, 101]
x_name: "Spatial Cuts rel."
x_regex: "-(\\d+)_"
output_img: "spatial_cut_effects.png"
output_csv: "data.csv"
title: "your nice title"
fontsize: 20
#log_x: true
#log_y: false
#do_annotate: true
#plot_errorbars: true
